server:
  port: 8081

# database ?? ??
spring:
  profiles:
    include: ignore

  # spring data jpa ??
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update